### ISSUE TITLE
Feature request | DNS command 

### ISSUE THREAD

**Issue by schtinkafinga** [Unicheckbot/unicheckbot#3]
### Command
---
`/dns domain.ltd`

It makes sense to include support for IP addresses as well as domains. IPs have DNS records like PTR, so adding a PTR output to a command like this would be logical:

`/dns 1.1.1.1`
response:
▫️PTR: 
   - Host: one.one.one.one

**Comment by kiriharu** [comment]
Added in newest release. 

At now, if resolver gets IP address, it try to get host by IP address. After this, host will be used in further DNS requests.
